version: '3.9'

services:
  # Database Admin UI (connects to Supabase)
  adminer:
    image: adminer:latest
    container_name: adminer_dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: ${SUPABASE_DB_HOST:-db.supabase.co}
      ADMINER_DESIGN: dracula

  # Mailhog (Email Testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_dev
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
    volumes:
      - mailhog_data:/maildir

  # Optional: Temporal (Workflow Engine)
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal_dev
    ports:
      - "7233:7233"
      - "8088:8088"
    environment:
      - SKIP_SCHEMA_SETUP=true
      - SKIP_DB_CREATE=true
    profiles:
      - temporal

  # Optional: Jaeger (Distributed Tracing)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_dev
    ports:
      - "16686:16686" # UI
      - "14268:14268" # HTTP
      - "6831:6831/udp" # UDP
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    profiles:
      - tracing

volumes:
  mailhog_data:

networks:
  default:
    name: qwik_dev_network