name = "qwik-lit-builder-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# KV Namespaces for Pages
[[kv_namespaces]]
binding = "KV"
id = "d7a33d626dfb43059f52828345a24efe"
preview_id = "dcf348d303684946ad6bb224348c2311"

# R2 Storage Buckets for Pages
[[r2_buckets]]
binding = "R2"
bucket_name = "qwik-production-files"

# Environment Variables
[vars]
DEPLOY_TARGET = "cloudflare"

# Development
[env.development]
vars = { ENVIRONMENT = "development" }

# Production  
[env.production]
vars = { ENVIRONMENT = "production" }

# Compatibility flags for Pages
compatibility_flags = ["nodejs_compat"]
