name = "qwik-lit-builder-app"
compatibility_date = "2025-01-28"
pages_build_output_dir = "dist"

# KV Namespaces for Pages
[[kv_namespaces]]
binding = "KV"
id = "d7a33d626dfb43059f52828345a24efe"
preview_id = "dcf348d303684946ad6bb224348c2311"

# R2 Storage Buckets for Pages
[[r2_buckets]]
binding = "R2"
bucket_name = "qwik-production-files"

# Environment Variables
[vars]
DEPLOY_TARGET = "cloudflare"
NODE_ENV = "production"
# Note: Sensitive environment variables are now configured in Cloudflare Pages dashboard:
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY  
# - VITE_SENTRY_DSN

# Preview (replaces development for Pages)
[env.preview.vars]
ENVIRONMENT = "preview"
NODE_ENV = "preview"
DEPLOY_TARGET = "cloudflare"
# Note: Sensitive environment variables are configured in Cloudflare Pages dashboard

[env.preview]
kv_namespaces = [
  { binding = "KV", id = "dcf348d303684946ad6bb224348c2311" }
]
r2_buckets = [
  { binding = "R2", bucket_name = "qwik-production-files" }
]

# Production  
[env.production.vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
DEPLOY_TARGET = "cloudflare"
# Note: Sensitive environment variables are configured in Cloudflare Pages dashboard

[env.production]
kv_namespaces = [
  { binding = "KV", id = "d7a33d626dfb43059f52828345a24efe" }
]
r2_buckets = [
  { binding = "R2", bucket_name = "qwik-production-files" }
]

# Compatibility flags for Pages
compatibility_flags = ["nodejs_compat"]
