// Test Fixtures - Generated by Migration
export const testUser = {
  id: '123e4567-e89b-12d3-a456-426614174000',
  email: 'test@example.com',
  name: 'Test User',
};

export const testFile = new File(['test content'], 'test.txt', { type: 'text/plain' });

export const createMockUser = (overrides = {}) => ({
  ...testUser,
  ...overrides,
});

export const createMockFile = (filename = 'test.txt', content = 'test', type = 'text/plain') => 
  new File([content], filename, { type });
